---
- hosts: servers
  environment:
    http_proxy: "http://{{ proxy_id }}:{{ proxy_pass }}@{{ proxy_url }}"
    https_proxy: "http://{{ proxy_id }}:{{ proxy_pass }}@{{ proxy_url }}"
  gather_facts: true
  become: true
  tasks:
    - name: Installation de la base de données
      ansible.builtin.include_role:
        name: "dbserver"
    - name: Installation de mediawiki
      ansible.builtin.include_role:
        name: "mediawiki"
    - name: Installation du serveur web
      ansible.builtin.include_role:
        name: "webserver"
  