---
ansible_user: administrateur

databases:
  - name: "mediawiki-db"
    encoding: "utf8"

databases_users:
  - name: "mediawiki-db-user"
    password: "superSecretPassword"

ports_http:
  - "80"
  - "443"

virtualhosts:
  - documentroot: "/var/www/html/mediawiki"
    port: "80"

mediawiki_db:
  name: "mediawiki-db"
  username: "mediawiki-db-user"
  password: "superSecretPassword"

mediawiki_name: "Le wiki de l'UTT"

php_versions:
  - "7.4"

php_modules:
  - php7.4-imagick
  - php7.4-mbstring
  - php7.4-xml
  - php7.4-mysqli
  - php7.4-mysql

mediawiki_is_already_installed: false

base_packages:
  - nano
  - netcat
  - zip
  - unzip
  - python3
  - python3-pip
  - git
  - vim
  - rsync
  - wget
  - curl