---
# tasks file for webserver
- name: Ajout du repo Apache
  ansible.builtin.apt_repository:
    repo: "{{ apache_repo }}"

- name: Installation d'Apache
  ansible.builtin.apt:
    name:
      - openssl
      - apache2
    state: latest
    update_cache: yes
    
- name: Vérification des permissions
  ansible.builtin.file:
    path: "{{ apache_base_path }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: true
  notify:
    - Restart Apache

- name: Ajout du repo PHP
  ansible.builtin.apt_repository:
    repo: "{{ php_repo }}"

- name: Installation des paquets PHP de base
  ansible.builtin.apt:
    name: php{{ item }}
  loop: "{{ php_versions }}"
  notify:
    - Restart Apache

- name: Installation des modules PHP
  notify:
    - Restart Apache
  ansible.builtin.apt:
    name: php{{ item.0 }}-{{ item.1 }}
  with_together:
    - "{{ php_versions }}"
    - "{{ php_modules }}"

- name: Configuration d'Apache
  ansible.builtin.template:
    owner: www-data
    src: sites.conf.j2
    dest: /etc/apache2/sites-enabled/sites.conf
  notify:
    - Restart Apache

- name: Suppresion du site par défaut d'Apache
  ansible.builtin.file:
    state: absent
    path: /etc/apache2/sites-enabled/000-default.conf
  notify:
    - Restart Apache

- name: Activation des modules Apache
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  loop: "{{ apache_modules }}"